spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
          simple:
            concurrency: 10
            max-concurrency: 20
            prefetch: 5

mq.env: local

log:
  user:
    queue.name: ${mq.env}.log.user.queue
    exchange.name: ${mq.env}.log.user.exchange
    routing.key.name: ${mq.env}.log.routing.key

#spring.rabbitmq.host=127.0.0.1
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.listener.simple.concurrency=10
#spring.rabbitmq.listener.simple.max-concurrency=20
#spring.rabbitmq.listener.simple.prefetch=5
#
#mq.env = local
#
#log.user.queue.name: ${mq.env}.log.user.queue
#log.user.exchange.name: ${mq.env}.log.user.exchange
#log.user.routing.key.name: ${mq.env}.log.user.routing.key

#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    listener:
#      simple:
#        acknowledge-mode: manual # 手动应答
#        concurrency: 5 # 消费端最小并发数
#        max-concurrency: 10 # 消费端最大并发数
#        prefetch: 5 # 一次请求中预处理的消息数量
#    cache:
#      channel:
#        size: 50 # 缓存的channel数量
#### 自定义配置
#mq:
#  defaultExchange: amqpExchange # 默认交换器
#  queue: queue # 队列名
#  routeKey: queue_key # 路由key